### PR TITLE
Moves GitOps to gitops branch

### PR DESCRIPTION
**Pull request by austinpray**
closes https://github.com/austinpray/kaori/issues/180

~All GitOps stuff is moved to https://github.com/austinpray/kaori-gitops and is already configured as such in the cluster.~

Gonna use https://github.com/austinpray/kaori/tree/gitops as the gitops branch

## notes for reviewer

- no lingering gitops related code in this branch
- how do the docs sound to you?

### CODE REVIEW

**Comment by austinpray** [comment]
Separate repo is actually kinda overkill: gonna just make a branch on this repo

**Comment by austinpray** [comment]
@ridhoq okay I deleted the gitops repo: now we are using an orphan branch

**Comment by ridhoq** [comment]
Did you do anything special wrt "orphaning" the branch?

**Comment by austinpray** [comment]
> Did you do anything special wrt "orphaning" the branch?

@ridhoq its an orphan branch with a completely new and disconnected history. `git checkout --orphan gitops`

Visual: https://github.com/austinpray/kaori/network

**Pull request merged**
